DESSAU.ControlGestion.Web/Models/ActividadModels/CrearEditarActividadViewModel.cs
using DESSAU.ControlGestion.Core;
using DESSAU.ControlGestion.Web.SelectListProviders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DESSAU.ControlGestion.Web.Models.ActividadModels
{
    public class CrearEditarActividadViewModel
    {
        public DESSAUControlGestionDataContext db = new DESSAUControlGestionDataContext()
            .WithConnectionStringFromConfiguration();
        public CrearEditarActividadFormModel Form { get; set; }
        public IEnumerable<Categoria> Categorias { get; set; }
        public IEnumerable<SelectListItem> TipoActividades { get; set; }
        private TipoActividadSelectListProvider taslp = new TipoActividadSelectListProvider();

        public CrearEditarActividadViewModel()
        {
            Form = new CrearEditarActividadFormModel();
            Categorias = db.Categorias.Where(x => x.Vigente).OrderBy(x => x.Nombre);
            TipoActividades = taslp.Provide();
        }

        public CrearEditarActividadViewModel(CrearEditarActividadFormModel form) : this()
        {
            Form = form;
        }
    }
}

DESSAU.ControlGestion.Web/Models/ActividadModels/ListarActividadViewModel.cs
using DESSAU.ControlGestion.Core;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DESSAU.ControlGestion.Web.Models.ActividadModels
{
    public class ListarActividadViewModel
    {
        public IPagedList<Actividad> Actividades { get; set; }
        public string filtro { get; set; }
    }
}

DESSAU.ControlGestion.Web/Controllers/ActividadController.cs
using DESSAU.ControlGestion.Core;
using DESSAU.ControlGestion.Web.Models.ActividadModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DESSAU.ControlGestion.Web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ActividadController : BaseController
    {
        public ActionResult Index()
        {
            return RedirectToAction("ListarActividad");
        }

        public ActionResult ListarActividad(int? pagina, string filtro)
        {
            ListarActividadViewModel model = new ListarActividadViewModel();
            model.filtro = filtro;
            IEnumerable<Actividad> Acts = db.Actividads
                .Where(x => x.Vigente == true)
                .OrderBy(x => x.IdTipoActividad)
                .ThenBy(x => x.Nombre);
            if (!String.IsNullOrEmpty(filtro))
            {
                filtro = filtro.ToLower();
                Acts = db.Actividads
                    .Where(x => x.Vigente == true && x.Nombre.ToLower().Contains(filtro));
            }
            model.Actividades = Acts.ToPagedList(pagina ?? 1, 10);
            return View(model);
        }

        public ActionResult CrearEditarActividad(int? IdActividad)
        {
            CrearEditarActividadViewModel model = new CrearEditarActividadViewModel();
            if (IdActividad.HasValue)
            {
                Actividad act = db.Actividads.Single(x => x.IdActividad == IdActividad);
                model.Form.NombreActividad = act.Nombre;
                model.Form.IdActividad = IdActividad;
                model.Form.IdTipoActividad = act.IdTipoActividad;
                //model.Form.IdCategorias = act.CategoriaActividads
                //    .Where(x => x.Vigente && x.Categoria.Vigente)
                //    .Select(x => x.IdCategoria).ToList();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult CrearEditarActividad(CrearEditarActividadFormModel Form)
        {
            //if(!Form.IdCategorias.Any())
            //{
            //    ModelState.AddModelError("", "Debe seleccionar al menos una Categoría.");
            //}
            if(ModelState.IsValid)
            {
                if (!Form.IdActividad.HasValue)
                {
                    Actividad act = new Actividad()
                    {
                        Nombre = Form.NombreActividad,
                        IdTipoActividad = Form.IdTipoActividad,
                        Vigente = true
                    };

                    db.Actividads.InsertOnSubmit(act);
                    //db.SubmitChanges();

                    //foreach (var idCategoria in Form.IdCategorias)
                    //{
                    //    CategoriaActividad catAct = new CategoriaActividad()
                    //    {
                    //        IdActividad = act.IdActividad,
                    //        IdCategoria = idCategoria,
                    //        Vigente = true
                    //    };

                    //    db.CategoriaActividads.InsertOnSubmit(catAct);
                    //}

                    db.SubmitChanges();
                    TempData["Mensaje"] = "La Actividad fue creada exitosamente. Recuerde asociar la Actividad a alguna Disciplina";
                    return RedirectToAction("ListarActividad");
                }
                else
                {
                    Actividad act = db.Actividads.Single(x => x.IdActividad == Form.IdActividad);
                    act.Nombre = Form.NombreActividad;
                    act.IdTipoActividad = Form.IdTipoActividad;

                    foreach(var item in act.CategoriaActividads)
                    {
                        item.Vigente = false;
                    }

                    //foreach (var IdCategoria in Form.IdCategorias)
                    //{
                    //    var hola = db.CategoriaActividads
                    //        .SingleOrDefault(x => x.IdActividad == act.IdActividad 
                    //        && x.IdCategoria == IdCategoria);
                    //    if (hola != null)
                    //    {
                    //        hola.Vigente = true;
                    //    }
                    //    else
                    //    {
                    //        CategoriaActividad catAct = new CategoriaActividad()
                    //        {
                    //            IdActividad = act.IdActividad,
                    //            IdCategoria = IdCategoria,
                    //            Vigente = true,
                    //        };

                    //        db.CategoriaActividads.InsertOnSubmit(catAct);
                    //    }           
                    //}

                    db.SubmitChanges();
                    TempData["Mensaje"] = "La Actividad fue editada exitosamente. Recuerde asociar la Actividad a alguna Disciplina.";
                    return RedirectToAction("ListarActividad");
                }
            }
            CrearEditarActividadViewModel model = new CrearEditarActividadViewModel(Form);
            return View(model);
        }
    }
}

DESSAU.ControlGestion.Web/Views/Actividad/CrearEditarActividad.cshtml
@model DESSAU.ControlGestion.Web.Models.ActividadModels.CrearEditarActividadViewModel

@{
    ViewBag.Title = "DESSAU";
}

@using (Html.BeginForm("CrearEditarActividad", "Actividad", FormMethod.Post, new { @class = "form-horizontal" }))
{
    if (Model.Form.IdActividad.HasValue)
    {
        @Html.HiddenFor(x => x.Form.IdActividad)
    }
    <div class="panel panel-primary">
        <div class="panel-heading">
            @if (Model.Form.IdActividad.HasValue)
            {
                <h4>Editar Actividad</h4>
            }
            else
            {
                <h4>Agregar Actividad</h4>
            }
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    @Html.ValidationSummary()
                    
                </div>
            </div>
            <div class="form-group">
                <label for="Nombre" class="col-md-2 control-label">@Html.LabelFor(x => x.Form.NombreActividad)</label>
                <div class="col-md-5">
                    <input type="text" class="form-control" id="Form_NombreActividad" name="Form.NombreActividad" placeholder="Nombre Actividad" value="@Model.Form.NombreActividad" />
                </div>
                <div class="col-md-5">
                    @Html.ValidationMessageFor(x => x.Form.NombreActividad)
                </div>
            </div>
            <div class="form-group">
                <label for="Nombre" class="col-md-2 control-label">@Html.LabelFor(x => x.Form.IdTipoActividad)</label>
                <div class="col-md-5">
                    @Html.DropDownListFor(x => x.Form.IdTipoActividad, Model.TipoActividades, "Seleccione un Tipo Actividad", new { @class = "form-control" })
                </div>
                <div class="col-md-5">
                    @Html.ValidationMessageFor(x => x.Form.IdTipoActividad)
                </div>
            </div>
        </div>
        @*<table class="table table-striped">
            <tr>
                <th class="col-md-2">
                </th>
                <th class="col-md-5">
                    Categorías
                </th>
            </tr>
            @{int i = 0;}         
            @foreach (var item in Model.Categorias)
            {
                <tr>
                    <td class="col-md-2">
                        @if (Model.Form.IdCategorias.Contains(item.IdCategoria))
                        {
                            <input checked="checked" type="checkbox" name="Form.IdCategorias[@i]" id="Form_IdCategorias[@i]"
                                   value="@item.IdCategoria" />
                        }
                        else
                        {
                            <input type="checkbox" name="Form.IdCategorias[@i]" id="Form_IdCategorias[@i]"
                                   value="@item.IdCategoria" />
                        }
                    </td>
                    <td class="col-md-5">
                        @(item.Nombre)
                    </td>
                </tr>
                i++;
            }
        </table>*@
    </div>
    <div class="row">
        <div class="col-md-3">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
}

DESSAU.ControlGestion.Web/Views/Actividad/ListarActividad.cshtml
@model DESSAU.ControlGestion.Web.Models.ActividadModels.ListarActividadViewModel

@{
    ViewBag.Title = "DESSAU";
}

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Actividades</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav"></ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Búsqueda amplia" name="filtro" id="input-filtro" value="@Model.filtro">
                </div>
                <button type="submit" class="btn btn-default">Buscar</button>
            </form>
            @Html.ActionLink("Agregar", "CrearEditarActividad", null, new { @class = "btn btn-primary navbar-btn navbar-right" })
        </div>
    </div>
</nav>

<div class="row">
    <div class="col-md-12">
        @Html.PagedListPager(Model.Actividades, page => Url.Action("ListarActividad", new
   {
       pagina = page,
       filtro = Model.filtro
   }))
        @(Html.Grid(Model.Actividades)
        .Attributes(@class => "table table-striped")
        .Columns(col =>
        {
            col.For(x => x.Nombre);
            col.For(x => x.TipoActividad.Nombre).Named("Tipo Actividad");
            col.For(x => Html.ButtonIconActionLink("pencil", "Editar Actividad", "CrearEditarActividad", null, null, new { IdActividad = x.IdActividad }));
        }).Empty("No se han encontrado registros asociados a los filtros seleccionados"))
    </div>
</div>